### Makefile -- Preparation of the Broken reference manual

# Broken (https://github.com/michipili/broken)
# This file is part of Broken
#
# Copyright © 2014–2015 Michael Grünewald
#
# This file must be used under the terms of the CeCILL-B.
# This source file is licensed as described in the file COPYING, which
# you should have received as part of this distribution. The terms
# are also available at
# http://www.cecill.info/licences/Licence_CeCILL-B_V1-en.txt

ODOC_TITLE=		Broken Testing Framework

ODOC_HTML_CSS_FILE=	${PROJECTLIBRARY}/Data/broken.css
ODOC_HTML_INTRO=	intro.text
ODOC_HTML_CHARSET=	utf-8

.include "ocaml.manual.mk"

### End of file `Makefile'
